"""add_soft_delete_to_user

Revision ID: 21befe77be08
Revises: 57c457fd2492
Create Date: 2026-02-23 20:18:50.186397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21befe77be08'
down_revision: Union[str, None] = '57c457fd2492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # [ZMIANA]: Usunięto kod kasujący tabelę password_reset_tokens!
    with op.batch_alter_table('users', schema=None) as batch_op:
        # [ZMIANA]: Dodano server_default='1', aby zapobiec błędowi w SQLite
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')
