"""Add onboarding flag to user_profiles

Revision ID: 24f4d8d8ec85
Revises: 872780760451
Create Date: 2026-04-17 19:19:53.673072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f4d8d8ec85'
down_revision: Union[str, None] = '872780760451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        # ================= [ZMIANA]: Dodanie server_default =================
        batch_op.add_column(
            sa.Column('is_onboarding_completed', sa.Boolean(), server_default='0', nullable=False)
        )
        # ====================================================================

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_onboarding_completed')

    # ### end Alembic commands ###