version: '3.8'

services:
  captcha-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./captcha.db
    volumes:
      - ./captcha.db:/app/captcha.db