"""Add creation time index to sentences table

Revision ID: d0933a804317
Revises: d1bad2db3dce
Create Date: 2026-04-30 11:58:09.116416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0933a804317'
down_revision: Union[str, Sequence[str], None] = 'd1bad2db3dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_sentences_lang_date', ['source_language', 'target_language', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index('ix_sentences_lang_date')
        batch_op.drop_index(batch_op.f('ix_sentences_created_at'))

    # ### end Alembic commands ###
